---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 01-automation-controller.yaml
  - 02-console-link.yaml
  - 03-automationhub.yaml
  - 04-automationhub-consolelink.yaml
  # - 05-automationhub-storageclass.yaml